search-icon mobile displpay hotfix
hlxsites/danaher-ls-aem pull request #1038
Opened 2024-04-17 14:08 UTC by amlan18041996

Fix #1032 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page
- After: https://1032-bug-search-prompt--danaher-ls-aem--hlxsites.hlx.page

2024-04-17 14:14 UTC, rgravitvl requested changes
<img width="289" alt="image" src="https://github.com/hlxsites/danaher-ls-aem/assets/12641714/bcf4ac2c-6598-4bbe-a7df-3b2c986ad317">

Its overlapping on carousel content. Ideally carousel content should push down when search bar appears. Refer below URL:
https://publish-p93411-e849552.adobeaemcloud.com/content/danaher/ls/us/en.html

2024-04-17 14:14 UTC, rgravitvl commented on blocks/header/header.js
> +    <svg data-v-7a6a1796="" class="w-8 h-8 md:hidden fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
Get this as a separate icon file in code base and use it

2024-04-17 14:14 UTC, rgravitvl commented on blocks/header/header.js
> +    { class: 'mobile-search w-full bg-black py-4 hidden md:hidden' },
remove hidden class as you kept md:hidden

2024-04-17 14:25 UTC, davenichols-DHLS approved these changes
Approved for when you have changed @rgravitvl 's feedback

2024-04-17 14:39 UTC, amlan18041996 commented on blocks/header/header.js
> +    { class: 'mobile-search w-full bg-black py-4 hidden md:hidden' },
> remove hidden class as you kept md:hidden

I have used hidden for toggle the search section on mobile only. However, md:hidden is used if from opened-state search suddenly changed to tablet/desktop screen then it will keep it hidden

2024-04-18 11:54 UTC, davenichols-DHLS commented
@rgravitvl  - if you have time can you please approve/review this and we can merge?

2024-04-19 06:45 UTC, rgravitvl approved these changes

2024-04-19 13:32 UTC, merged