1051 [SEO] Library Page Fix and CSS split by Block
hlxsites/danaher-ls-aem pull request #1062
Opened 2024-04-23 12:24 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #1051 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://1051-css-split-library--danaher-ls-aem--hlxsites.hlx.page/us/en/library/antibodies
- After: https://1051-css-split-library--danaher-ls-aem--hlxsites.hlx.page/us/en/library/antibody-generation-hybridoma

2024-04-24 10:44 UTC, rgravitvl requested changes

2024-04-24 10:44 UTC, rgravitvl commented on templates/library/library-dev.css
> -  @apply px-6 xl:pl-0;
Did you add this to JS ?

2024-04-24 10:44 UTC, rgravitvl commented on templates/library/library-dev.css
> -  @apply lg:w-recent-articles-left;
Did you add this to JS ?

2024-04-24 10:44 UTC, rgravitvl commented on templates/library/library-dev.css
> -  @apply !text-2xl p-0 m-0 tracking-tight sm:text-3xl text-white font-normal tracking-wide;
Did you add this to JS ?

2024-04-24 11:33 UTC, sharanagoudapatil commented on templates/library/library-dev.css
> -  @apply !text-2xl p-0 m-0 tracking-tight sm:text-3xl text-white font-normal tracking-wide;
This was added in call-toaction.js, so no need to add here again. So removed this.

2024-04-24 11:36 UTC, sharanagoudapatil commented on templates/library/library-dev.css
> -  @apply lg:w-recent-articles-left;
updated under 'columns-dev.css' as it there was same code added for .blog main like below,
![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/4ad2b2e5-8820-4a1b-9942-3fc90b72bdd5)

2024-04-25 08:00 UTC, davenichols-DHLS approved these changes
Looking good in the front end.  @rgravitvl  - please can you confirm.

2024-04-25 08:13 UTC, rgravitvl approved these changes

2024-04-25 08:20 UTC, merged