1040 Topic's header ReBrand changes
hlxsites/danaher-ls-aem pull request #1066
Opened 2024-04-24 10:40 UTC by amlan18041996

Fix #1040 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers/topics/what-is-mass-spectrometry
- After: https://1040-header-topic-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/products/mass-spectrometers/topics/what-is-mass-spectrometry

2024-04-25 04:06 UTC, rgravitvl approved these changes

2024-04-25 12:18 UTC, sharanagoudapatil approved these changes
Approved. But one small suggestion - can we make use of the right side space ?  
Please check this page
![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/c74a1a2a-477f-4a4c-bb60-d255eeaf7b28)

2024-04-25 12:21 UTC, amlan18041996 commented
Changes applied 50% based on figma design

2024-04-29 11:13 UTC, rgravitvl requested changes

2024-04-29 11:13 UTC, rgravitvl commented on blocks/side-nav/side-nav.js
> +  console.log(block, block.parentElement);
Remove console log

2024-05-30 09:06 UTC, davenichols-DHLS commented
I am approving, but the CLS appears worse on this change than on current prod.

Current:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-products-flow-cytometers-topics-sheath-fluid-flow-cytometry-html/co467ygogc?form_factor=mobile
This Branch:  https://pagespeed.web.dev/analysis/https-1040-header-topic-pages--danaher-ls-aem--hlxsites-hlx-page-us-en-products-flow-cytometers-topics-sheath-fluid-flow-cytometry/dpl8it3ede?form_factor=mobile

2024-05-30 09:06 UTC, davenichols-DHLS approved these changes
Approved.  @amlan18041996  - can you please fix the conflicts.

2024-05-30 10:34 UTC, davenichols-DHLS commented
@amlan18041996  - are you able to please fix the conflicts and then I will merge this?  Thanks.

2024-05-31 04:23 UTC, merged