[UE] improve authoring experience
hlxsites/danaher-ls-aem pull request #1206
Opened 2024-07-09 13:15 UTC by jckautzmann

- the logic in the blocks assumes EDS paths. As the same logic is used on the AEM author instance, they need to be adapted

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #1083 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://ue-authoring-2--danaher-ls-aem--hlxsites.hlx.page/

2024-07-09 13:49 UTC, rgravitvl requested changes

2024-07-09 13:49 UTC, rgravitvl commented on scripts/lib-franklin-dev.js
> +  const meta = [...document.head.querySelectorAll(`meta[${attr}="${name}" i]`)].map((m) => m.content).join(', ');
Hi @jckautzmann , Is this added intentionally?

2024-07-09 14:14 UTC, jckautzmann commented on scripts/lib-franklin-dev.js
> +  const meta = [...document.head.querySelectorAll(`meta[${attr}="${name}" i]`)].map((m) => m.content).join(', ');
yes, I added it temporarily to work around an issue in AEM, as the metadata property names generated by AEM are currently case sensitive. The issue has been fixed and is going to be deployed in a future AEM release.

2024-07-10 04:50 UTC, rgravitvl approved these changes

2024-07-10 09:37 UTC, merged