feat: implement blog page styles
hlxsites/danaher-ls-aem pull request #171
Opened 2023-10-02 15:09 UTC by duynguyen

Fix #151 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-cell-painting-making-mark
- After: https://151-blog-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-cell-painting-making-mark

2023-10-05 13:57 UTC, rgravitvl requested changes

2023-10-05 13:57 UTC, rgravitvl commented on templates/blog/blog.js
> +    }
Below page fails to render all the content. Above can go as static if check.
https://151-blog-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency

2023-10-05 17:35 UTC, duynguyen commented on templates/blog/blog.js
> +    }
good spot @rgravitvl , fixed

2023-10-06 08:06 UTC, davenichols-DHLS commented
Hi @duynguyen  and @rgravitvl .  Looking great, but I noticed that some pictures within the content are not having the correct ratio?  

Example:  https://151-blog-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency vs https://lifesciences.danaher.com/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency.html

2023-10-06 08:59 UTC, duynguyen commented
@davenichols-DHLS it seems to be from the columns block. created #183 to follow up.

2023-10-06 09:24 UTC, davenichols-DHLS approved these changes
Looks good - will add another task for updating small fixes.

2023-10-06 09:25 UTC, rgravitvl approved these changes

2023-10-06 09:25 UTC, merged