159 implement converter product pages
hlxsites/danaher-ls-aem pull request #175
Opened 2023-10-04 08:00 UTC by rgravitvl

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix # 159

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://159-implement-converter-product-pages--danaher-ls-aem--hlxsites.hlx.page/

2023-10-04 12:30 UTC, Buuhuu requested changes

2023-10-04 12:30 UTC, Buuhuu commented on tools/actions/convert/test/fixtures/product-semantic.html
> +      <div class="section-metadata">
Each tab should have its own section. So it should be something like

```
<html>
<body>
  <header></header>
  <main>
    <div>
      <div class="product-details">
        <div>
          <div>Request for Quote</div>
        </div>
      </div>
   </div>
   <div>
      <div class="section-metadata">
      ...
   </div>
   <div>
      <div class="section-metadata">
      ...
```

2023-10-05 17:32 UTC, rgravitvl commented on tools/actions/convert/test/fixtures/product-semantic.html
> +      <div class="section-metadata">
Done

2023-10-06 09:46 UTC, Buuhuu commented on tools/actions/convert/test/fixtures/product-semantic.html
> +      <div class="section-metadata">
It still seems to be all in the same section. did you update the test html?

2023-10-06 14:04 UTC, duynguyen commented on tools/actions/convert/test/fixtures/product-semantic.html
> +      <div class="section-metadata">
AFAICS this test html is just fine, because the <hr> will take care of separating the sections.

Example semantic MD:
```
+-------------------+
| Product Details   |
+===================+
| Request for Quote |
+-------------------+

---

![][image0]

+----------------------------------------------------------+
| Section Metadata                                         |
+=========+================================================+
| icon    | /content/dam/danaher/system/icons/Bookmark.svg |
+---------+------------------------------------------------+
| tabId   | overview                                       |
+---------+------------------------------------------------+
| tabName | Overview                                       |
+---------+------------------------------------------------+

---

+-----------------------------------------------------+
| product-attribute-table                             |
+===========================+=========================+
| Capability                | capability              |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Dimensions                | dimensions              |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Imaging                   | imaging                 |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Instrumentation           | instrumentation         |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Materials of Construction | materialsofconstruction |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Regulatory                | regulatory              |
+-----------------------------------------------------+
| product-attribute-table                             |
+---------------------------+-------------------------+
| Specifications            | specifications          |
+---------------------------+-------------------------+

![][image1]

+-----------------------------------------------------------+
| Section Metadata                                          |
+=========+=================================================+
| icon    | /content/dam/danaher/system/icons/Chart bar.svg |
+---------+-------------------------------------------------+
| tabId   | specification                                   |
+---------+-------------------------------------------------+
| tabName | Specifications                                  |
+---------+-------------------------------------------------+

---

+----------------------------------------------------------+
| Section Metadata                                         |
+=========+================================================+
| icon    | /content/dam/danaher/system/icons/Document.svg |
+---------+------------------------------------------------+
| tabId   | resources                                      |
+---------+------------------------------------------------+
| tabName | Resources                                      |
+---------+------------------------------------------------+

---

+------------------------------+
| Metadata                     |
+=======+======================+
| Title | Default Product Page |
+-------+----------------------+

[image0]: https://s7d9.scene7.com/is/image/danaherstage/petri-dish

[image1]: https://s7d9.scene7.com/is/image/danaherstage/transfection
```

This will be served by the pipeline to the final HTML as you mentioned above. I compared the other pages such as [Home](https://github.com/hlxsites/danaher-ls-aem/blob/main/tools/actions/convert/test/fixtures/en-semantic.html) as don't see anything different from this.

2023-10-06 15:01 UTC, duynguyen approved these changes
LGTM.
Some minor comments:
- you could remove the last `hr>` in between the section metadata and metadata, which might add unexpected div at the end of the page
- Not sure the purpose of "Request for Quote" in the `product-details` block. I guess you @rgravitvl and @Buuhuu discussed this already so there might be reasons behind it that I'm not aware of. We can keep it as is and adjust if needed.

2023-10-06 15:16 UTC, Buuhuu commented on tools/actions/convert/test/fixtures/product-semantic.html
> +      <div class="section-metadata">
Got it, thanks.

2023-10-06 15:18 UTC, Buuhuu approved these changes

2023-10-07 04:58 UTC, merged