feat: base styles
hlxsites/danaher-ls-aem pull request #22
Opened 2023-08-29 12:07 UTC by dicagno

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #5 

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.page/
- After: https://<branch>--{repo}--{owner}.hlx.page/

2023-08-29 12:27 UTC, mhaack commented on styles/styles.css
> +}
Where these are needed? Lets not re-build tailwind style classes if we don't need these.

2023-08-29 14:10 UTC, dicagno commented on styles/styles.css
> +}
Makes sense, we can directly link the custom properties where needed

2023-08-30 07:19 UTC, mhaack requested changes

2023-08-30 07:19 UTC, mhaack commented on styles/lazy-styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
Lets add the fonts directly to the projects, also make sure we have matching fallback fonts.

2023-08-30 07:19 UTC, mhaack commented on blocks/cards/cards.css
This should not be here as not really part of global styles. Lets do this via #10. Anyway, lets keep it as a base version for the cards block.

2023-08-30 07:19 UTC, mhaack commented on styles/styles.css
> +  --heading-font-family: fort, inter, roboto-fallback;
Make sure we have the correct fallback fonts.

2023-08-30 07:19 UTC, mhaack commented on styles/styles.css
> +}
Please remove, this can be added via individual block classes.

2023-08-30 07:31 UTC, dicagno commented on blocks/cards/cards.css
Yeah, that's exactly why i implemented some basics as part of this task, to get a basic styling for cards as well.

2023-08-30 07:33 UTC, dicagno commented on styles/lazy-styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
For Inter, this should be possible; for Fort, this is a licensed font available in Adobe Fonts, so we have to use the hosted TypeKit css

2023-08-30 07:34 UTC, dicagno commented on styles/styles.css
> +  --heading-font-family: fort, inter, roboto-fallback;
Yes, will check this, thanks

2023-08-30 07:35 UTC, dicagno commented on styles/styles.css
> +}
Part of the task was about defining font sizes. Do you confirm these are not needed anymore in global styles?

2023-08-30 07:53 UTC, mhaack commented on styles/lazy-styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
Hm think you are right.

2023-08-31 12:39 UTC, mhaack commented on styles/fonts.css
> +  src: url('../fonts/roboto-regular.woff2') format('woff2');
This font is still missing  in the fonts folder

2023-08-31 12:39 UTC, mhaack commented on styles/fonts.css
> +  src: url('../fonts/roboto-bold.woff2') format('woff2');
This font is still missing  in the fonts folder

2023-08-31 12:50 UTC, dicagno commented on styles/fonts.css
> +  src: url('../fonts/roboto-regular.woff2') format('woff2');
All the fonts are included in https://github.com/hlxsites/danaher-ls-aem/tree/4d96a8bc11690c4bd6a2c4caa192dd0cba6cfb89/fonts

Are you referring to the font files?

2023-08-31 13:03 UTC, mhaack commented on styles/fonts.css
> +  src: url('../fonts/roboto-regular.woff2') format('woff2');
👍

2023-08-31 13:06 UTC, mhaack commented on styles/fonts.css
> +  src: url('../fonts/inter-regular.ttf') format('truetype');
Why using older ttf font here, the original site loads https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2 for me?

2023-08-31 13:12 UTC, dicagno commented on styles/fonts.css
> +  src: url('../fonts/inter-regular.ttf') format('truetype');
If you try to download the official font pack from Google fonts, it only provides TTFs, that's why I used this format.
Aside from compression benefits, Is it a major concern? Just asking to know, more in general

2023-08-31 13:15 UTC, mhaack commented
One more aspect: I see original uses tailwind "max-w-7xl" as max with for all major elements on the site, with "mx-auto" to keep it centered. We have it centered already but should go with "max-width: 80rem;" as well for our divs inside the sections

2023-08-31 13:44 UTC, mhaack commented on styles/fonts.css
> +  src: url('../fonts/inter-regular.ttf') format('truetype');
Interesting as woff2 is provided is used directly from Google. Let’s then as the Danaher colleagues on Slack.

2023-08-31 13:45 UTC, dicagno commented on styles/fonts.css
> +  src: url('../fonts/inter-regular.ttf') format('truetype');
yeah that's true, it's unusual. let's ask them then :)

2023-09-01 08:27 UTC, mhaack approved these changes

2023-09-01 08:29 UTC, merged