initial commit
hlxsites/danaher-ls-aem pull request #243
Opened 2023-10-19 13:37 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://210-mapping-page-meta-keywords--danaher-ls-aem--hlxsites.hlx.page/

2023-10-19 13:44 UTC, rgravitvl requested changes

2023-10-19 13:51 UTC, sharanagoudapatil commented on tools/importer/import.js
> +    meta.Title = title.textContent.replace(/[\n\t]/gm, '').replace('| Danaher Lifesciences', '').replace('| Danaher Life Sciences', '').trim();
@rgravitvl - Yes, I've changed in the converter (import.js) itself rather than yaml file.

2023-10-19 13:54 UTC, davenichols-DHLS commented on tools/importer/import.js
> +    meta.Title = title.textContent.replace(/[\n\t]/gm, '').replace('| Danaher Lifesciences', '').replace('| Danaher Life Sciences', '').trim();
@sharanagoudapatil  - on the tags I can see it coming through, but on here it is showing a special character - @mhaack would this be an issue?  FYI @rgravitvl 

Example:  view-source:https://210-mapping-page-meta-keywords--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/transition-away-from-animal-testing-could-mean-drug-discovery

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/ddcf85a9-c0bd-4533-ae44-265c9414708b)

2023-10-19 14:24 UTC, sharanagoudapatil commented on tools/importer/import.js
> +    meta.Title = title.textContent.replace(/[\n\t]/gm, '').replace('| Danaher Lifesciences', '').replace('| Danaher Life Sciences', '').trim();
@rgravitvl  and @mhaack - I've reverted the changes and made changes only in yaml file. Please have a look. thanks.

cc: @davenichols-DHLS

2023-10-19 14:42 UTC, mhaack commented on helix-query.yaml
> +        value: replace(attribute(el, "content"),"| Danaher Life Sciences", "").replace(attribute(el, "content"),"| Danaher Lifesciences", "")
Why are there 2 replace calls?

2023-10-19 14:56 UTC, mhaack commented on tools/importer/import.js
> +    meta.Title = title.textContent.replace(/[\n\t]/gm, '').replace('| Danaher Lifesciences', '').replace('| Danaher Life Sciences', '').trim();
> @sharanagoudapatil If you change here, the page title will also impact. So we should not change it here, rather we can change it in yaml file.
> 
> @mhaack correct me if I am wrong.

No this change is only for the indexing. In the converter I think we should keep it as we want to have it in the <title> of the page.

2023-10-19 15:03 UTC, sharanagoudapatil commented on helix-query.yaml
> +        value: replace(attribute(el, "content"),"| Danaher Life Sciences", "").replace(attribute(el, "content"),"| Danaher Lifesciences", "")
@mhaack - Some of the pages having 'Danaher Life Sciences' and on pages they have 'Danaher Lifesciences'. So, it's a double check both the strings.

2023-10-19 15:13 UTC, mhaack approved these changes

2023-10-19 15:13 UTC, mhaack commented on helix-query.yaml
> +        value: replace(attribute(el, "content"),"| Danaher Life Sciences", "").replace(attribute(el, "content"),"| Danaher Lifesciences", "")
Ahh sorry I missed that it is two versions

2023-10-20 05:26 UTC, rgravitvl approved these changes

2023-10-20 05:53 UTC, merged