308-ctasection-block
hlxsites/danaher-ls-aem pull request #326
Opened 2023-11-02 09:55 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://308-ctasection-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges

2023-11-02 10:04 UTC, sharanagoudapatil commented
Hi @deepakk799 - I've pushed my changes with a 'Request a Quote' popup base Modal. Please have a look. 
You can use this same branch for further changes. Thanks.

2023-11-02 14:20 UTC, mhaack commented on package.json
> +    "dev": "concurrently --kill-others \"postcss ./styles/tailwind.css --output ./styles/styles.css --watch\" \"aem up \"",
Let keep `--print-index`

2023-11-02 14:25 UTC, mhaack commented on styles/modal/modal.css
Can you try to get the styles applied as tailwind classes in the modal.js please. As we create the `<button name="close"><span class="close-x"></span></button>` element we can add the styles there directly.

2023-11-07 09:26 UTC, mhaack commented on scripts/scripts.js
> +      p({ class: 'close-button', name: 'close' }, span({ class: 'icon icon-icon-close cursor-pointer' })),
Should we rename the icon to `close.svg` so we can use `icon-close` class? Double "icon" looks wrong.

2023-11-07 09:26 UTC, mhaack commented on scripts/scripts.js
> +  const quoteModalContent = () => div(
I think we should move the individual modal functions to modal.js. When we get more of them scripts.js will get bigger and bigger

2023-11-08 01:17 UTC, deepakk799 commented on scripts/scripts.js
> +      p({ class: 'close-button', name: 'close' }, span({ class: 'icon icon-icon-close cursor-pointer' })),
I thought to the same, there are few others named like that.. I'm not sure if we want to change all and how would it affect to the pages.

2023-11-08 10:49 UTC, duynguyen commented on blocks/ctasection/ctasection.js
> +  block.querySelector('div').querySelector('div').querySelector('h2').classList = 'text-2xl p-0 m-0 tracking-tight sm:text-3xl text-white font-normal';
instead of multiple querySelector calls, you can do it once with multiple element levels.
e.g. `block.querySelector('div h2')`, or if you know it's 2 levels down e.g. `block.querySelector(':scope > div > div > h2')`

2023-11-08 10:54 UTC, duynguyen commented on scripts/modal.js
> +    const quoteModalContent = () => div(
just an idea, you can do it now or later: this part seems reusable not only for quote but also for other places. so you can make this `buildModalContent` generic and move the rest of quote specific to a quote-modal.js file

2023-11-08 10:55 UTC, mhaack requested changes

2023-11-08 10:55 UTC, mhaack commented on scripts/modal.js
> +      const country = document.querySelector('meta[name="country"]')?.getAttribute('content');
For all meta data use `getMetadata()` helper.

2023-11-08 10:55 UTC, mhaack commented on scripts/toast.js
> +      img({ class: 'w-24 h-24 rounded shadow-lg', src: addedProduct.image ? addedProduct.image : 'https://dev.lifesciences.danaher.com/content/dam/danaher/system/no-image-availble.jpg' }),
We should not hard code a dev url. We have a the default image [default-meta-image.png](https://github.com/hlxsites/danaher-ls-aem/blob/main/default-meta-image.png) which should be used here.

2023-11-08 10:55 UTC, mhaack commented on scripts/modal.js
> +function getAuthorization() {
We have `getAuthorization` here already https://github.com/hlxsites/danaher-ls-aem/blob/main/scripts/scripts.js#L402

2023-11-08 10:55 UTC, mhaack commented on scripts/modal.js
> +function getCookie(cname) {
We have `getCookie` already defined https://github.com/hlxsites/danaher-ls-aem/blob/main/scripts/scripts.js#L402

2023-11-08 10:57 UTC, duynguyen commented on styles/modal/modal.css
> +.modal-title span.icon {
these styles could be added directly to the JS markup where you build the modal content.

2023-11-08 13:07 UTC, deepakk799 commented on scripts/modal.js
> +function getCookie(cname) {
I did include but got lint error; let me know how to get around it, shall we move these common functions into a seprate JS
error  Dependency cycle detected  import/no-cycle we are importing modal.js into script.js and vice versa.

2023-11-08 13:08 UTC, deepakk799 commented on scripts/modal.js
> +function getAuthorization() {
same a above function.

2023-11-08 13:09 UTC, deepakk799 commented on scripts/modal.js
> +      const country = document.querySelector('meta[name="country"]')?.getAttribute('content');
yes, meta won't be used here.. will update it to read it from the button props when we build it for family/sku product pages

2023-11-09 09:19 UTC, davenichols-DHLS commented on scripts/modal.js
> +      const country = document.querySelector('meta[name="country"]')?.getAttribute('content');
@mhaack - can you please re-review now that Deepak made the changes?

2023-11-09 12:15 UTC, mhaack requested changes

2023-11-09 12:15 UTC, mhaack commented on blocks/ctasection/ctasection.css
> +}
Lets not add files we don't need

2023-11-09 12:15 UTC, mhaack commented on blocks/ctasection/ctasection.js
> +  block.querySelector('p').classList = 'show-modal-btn btn btn-outline-trending-brand rounded-full px-6 py-3';
This is wrong, should be `.classList.add(..)`. `classList` is an array you cannot set a string here.

2023-11-09 12:15 UTC, mhaack commented on scripts/utils.js
I would keep the getCookie & setCookie in scripst.js and create the util only for "commerce related" stuff. Maybe the also rename the file, `utils.js` can be anything.

2023-11-09 12:15 UTC, mhaack commented on blocks/ctasection/ctasection.js
Please rename back to `cta` or `callToAction` as this is a block, should not have section in the name.

2023-11-09 14:13 UTC, deepakk799 commented on blocks/ctasection/ctasection.css
> +}
I saw 404 error as the block code was looking for it, I'll delete.. lets see if its different in remote.

2023-11-10 05:42 UTC, rgravitvl commented
@deepakk799/ @sharanagoudapatil Looks like CTA Section is broken now, please check.

2023-11-10 05:55 UTC, sharanagoudapatil commented
@rgravitvl - After merging of the rename CTASection converter code PR, it is working fine now. Please verify. Thanks.

2023-11-10 05:57 UTC, rgravitvl approved these changes

2023-11-10 09:47 UTC, duynguyen commented on scripts/commerce.js
> +export function getCookie(cname) {
as Markus mentioned earlier, get and set cookie function should be kept in scripts.js because they are also used outside of the commerce use case.

2023-11-10 11:05 UTC, mhaack approved these changes

2023-11-10 11:43 UTC, merged