327 accordion UI block
hlxsites/danaher-ls-aem pull request #338
Opened 2023-11-03 06:27 UTC by rgravitvl

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #327 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://327-accordion-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products/centrifuges

2023-11-03 09:30 UTC, sharanagoudapatil approved these changes
Changes looks good to me. Thanks.

2023-11-03 09:33 UTC, mhaack commented on blocks/accordion/accordion.js
> +    p({ class: 'text-base leading-7 text-gray-600 href-text v-html' }),
`v-html` is a left over from old css

2023-11-03 09:34 UTC, mhaack requested changes

2023-11-03 09:34 UTC, mhaack commented on blocks/accordion/accordion.js
> +  btn.querySelector('span').innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="chevy ml-2 h-5 w-5 transition"><path fill-rule="even
`chevy` is a left over from old css, right?

2023-11-03 09:37 UTC, duynguyen commented on blocks/accordion/accordion.js
> +    { id: buttonId, class: 'close button' },
If there're 2 accordion blocks on the same page, the button and panel IDs would be duplicate.
do we need ID here? if not let's remove it.

2023-11-03 10:16 UTC, rgravitvl commented on blocks/accordion/accordion.js
> +    p({ class: 'text-base leading-7 text-gray-600 href-text v-html' }),
Removed

2023-11-03 10:16 UTC, rgravitvl commented on blocks/accordion/accordion.js
> +  btn.querySelector('span').innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="chevy ml-2 h-5 w-5 transition"><path fill-rule="even
Removed

2023-11-03 10:16 UTC, rgravitvl commented on blocks/accordion/accordion.js
> +    { id: buttonId, class: 'close button' },
Removed Id

2023-11-03 10:18 UTC, rgravitvl commented on blocks/accordion/accordion.js
> +  const isOpen = activeButton.classList.contains('open');
where do we implemented aria-expanded before? I mean any reference?

2023-11-03 11:01 UTC, mhaack commented on blocks/accordion/accordion.js
> +  const isOpen = activeButton.classList.contains('open');
See https://github.com/hlxsites/moleculardevices/blob/main/blocks/accordion/accordion.js look for `openAttribute`

2023-11-06 21:15 UTC, duynguyen approved these changes

2023-11-07 08:47 UTC, merged