284 related articles UI block
hlxsites/danaher-ls-aem pull request #343
Opened 2023-11-03 12:07 UTC by rgravitvl

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #284 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/industrializing-biology-biopharma-4
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/how-organoids-can-redefine-pre-clinical-research
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/lab-tools-enhance-mrna-development-manufacturing-efficiency
- After: https://284-related-articles-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/the-ai-powered-pixel-classifier

2023-11-03 12:51 UTC, mhaack requested changes

2023-11-03 12:51 UTC, mhaack commented on blocks/related-articles/related-articles.js
> +  let articles = await ffetch('/us/en/query-index.json')
This should now be `article-index` :-)

2023-11-03 12:51 UTC, mhaack commented on scripts/scripts.js
> +export function imageHelper(imageUrl, imageAlt, eager = false) {
This looks similar to https://github.com/hlxsites/danaher-ls-aem/blob/main/blocks/card-list/card-list.js#L11 please update card-list as well to use the method moved to scripts.js

2023-11-03 12:51 UTC, mhaack commented on blocks/related-articles/related-articles.js
> +const createCard = (article, firstCard = false) => {
Is this a copy of https://github.com/hlxsites/danaher-ls-aem/blob/main/blocks/card-list/card-list.js#L29C9-L29C9? we should export the function on card-list and import it here.

2023-11-03 12:55 UTC, rgravitvl commented on blocks/related-articles/related-articles.js
> +const createCard = (article, firstCard = false) => {
updated the style a bit and removed read article text, any way I will confirm the changes with @davenichols-DHLS

2023-11-03 12:59 UTC, mhaack commented on blocks/related-articles/related-articles.js
> +const createCard = (article, firstCard = false) => {
Maybe we can have one createCard method which supports both styles with some optional parameters.

2023-11-03 13:01 UTC, rgravitvl commented on blocks/related-articles/related-articles.js
> +  let articles = await ffetch('/us/en/query-index.json')
Done

2023-11-03 13:01 UTC, rgravitvl commented on scripts/scripts.js
> +export function imageHelper(imageUrl, imageAlt, eager = false) {
Done

2023-11-03 17:31 UTC, rgravitvl commented on blocks/related-articles/related-articles.js
> +const createCard = (article, firstCard = false) => {
@mhaack As discussed with @davenichols-DHLS , we are good with Card from hub page. So I just exported the createCard from card-list.

2023-11-04 14:15 UTC, mhaack approved these changes

2023-11-06 05:41 UTC, merged