feat: implement sidebar topic list
hlxsites/danaher-ls-aem pull request #440
Opened 2023-11-16 16:31 UTC by duynguyen

Fix #419 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/what-are-assay-kits
- After: https://419--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/what-are-assay-kits

2023-11-16 16:45 UTC, davenichols-DHLS approved these changes
I love this, thank you!

2023-11-16 17:29 UTC, davenichols-DHLS requested changes
Thank you @duynguyen , this is fantastic, but sorry, can I ask for a few changes please?

- Hide left bar on mobile view, like we do with the right bar on blogs/news
- Can we add a hover over of purple-25 (sorry this was missed on the UX)
- Reduce the left hand bar to 25% of width

2023-11-17 06:42 UTC, sharanagoudapatil commented
@duynguyen - Please verify for these 2 pages, social-media links still not working as expected
 
https://419--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/how-are-assay-kits-installed 
https://419--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/what-are-assay-kits 

![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/48c746fd-85cc-4b64-a2b7-29b79cd6925f)

2023-11-21 08:32 UTC, mhaack approved these changes

2023-11-21 08:35 UTC, mhaack commented on blocks/side-nav/side-nav.js
> +  return products.sort((item1, item2) => item1.title.localeCompare(item2.title));
Better rename to "category" as these are not products.

2023-11-21 11:47 UTC, duynguyen commented on blocks/side-nav/side-nav.js
> +  return products.sort((item1, item2) => item1.title.localeCompare(item2.title));
done

2023-11-21 12:13 UTC, mhaack commented on blocks/side-nav/side-nav.js
> +    .filter(({ type, path }) => type === 'TopicHub' && path.endsWith('/topics'))
The check `path.endsWith('/topics')` is not needed any more right?

2023-11-21 13:14 UTC, duynguyen commented on blocks/side-nav/side-nav.js
> +    .filter(({ type, path }) => type === 'TopicHub' && path.endsWith('/topics'))
fixed, thanks

2023-11-21 13:16 UTC, merged