Implement template for library pages
hlxsites/danaher-ls-aem pull request #477
Opened 2023-11-22 12:22 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://implement-template-for-library-pages--danaher-ls-aem--hlxsites.hlx.page/us/en/library/organoids

2023-11-22 13:15 UTC, duynguyen commented on templates/library/library.css
> +.library main {
If these styles are shared with other templates (blog / news, etc.) they should be moved to tailwind.css and only declared once.

2023-11-22 13:16 UTC, duynguyen commented on templates/library/library.css
> +.library main .section a {
AFAICS the styling of certain elements (a, ul, ol, img) are similar in default-content-wrapper. Can we make them global, same as we do for headings?

2023-11-22 13:22 UTC, davenichols-DHLS approved these changes
Looks good to me.  @duynguyen  - would you mind please quickly reviewing?

2023-11-22 13:31 UTC, duynguyen requested changes

2023-11-22 13:31 UTC, duynguyen commented on templates/library/library.js
> +  main.prepend(block);
why prepend block here? in templates, the block param here is already main.

2023-11-22 15:42 UTC, davenichols-DHLS commented on templates/library/library.js
> +  main.prepend(block);
@sharanagoudapatil  or @amlan18041996  - can you please comment?

2023-11-22 16:32 UTC, rgravitvl commented
@sharanagoudapatil and @amlan18041996 I can see CTA is broken, please check that as well.

2023-11-23 05:49 UTC, sharanagoudapatil commented on templates/library/library.js
> +  main.prepend(block);
Removed the library.js code now as it is not required.

2023-11-23 06:05 UTC, sharanagoudapatil commented on templates/library/library.css
> +.library main {
Removed '.library main' block of code as it is not required and remaining code kept in the library.css which are not common. 
Please confirm/let me know if you want to move everything from library.css to tailwind.css?

2023-11-23 06:06 UTC, sharanagoudapatil commented
@rgravitvl - CTA button is fixed now. Please check now.

2023-11-23 08:19 UTC, duynguyen reviewed
@sharanagoudapatil overall it looks good. I think we can still simplify the CSS especially many of the styles are shared with topic and blog template. wdyt?

2023-11-23 08:19 UTC, duynguyen commented on templates/library/library.css
> +.library main .section > .default-content-wrapper > h2 {
should be removed because it's declared in the global heading styles

2023-11-23 08:19 UTC, duynguyen commented on templates/library/library.css
> +.library main > div:first-child .default-content-wrapper h1 {
should only add the styles not already set by global heading

2023-11-23 08:19 UTC, duynguyen commented on templates/library/library.css
> +  @apply btn-outline-trending-brand text-lg px-6 py-2.5 my-8 rounded-full;
this is exactly the same as in topic.css. If applied globally, can we move it to tailwind.css?

2023-11-23 10:31 UTC, duynguyen approved these changes

2023-11-23 11:24 UTC, rgravitvl approved these changes

2023-11-23 11:25 UTC, merged