507 product category list block
hlxsites/danaher-ls-aem pull request #533
Opened 2023-11-30 17:44 UTC by rgravitvl

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #507 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
- After: https://507-product-category-list-block--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
- After: https://507-product-category-list-block--danaher-ls-aem--hlxsites.hlx.page/us/en/product2

2023-12-01 09:49 UTC, mhaack requested changes

2023-12-01 09:49 UTC, mhaack commented on blocks/product-category-list/product-category-list.js
> +  if (activeTagFilter) {
Additionally you need to filter for type = Category to show only categories. Right know also topic pages are shown.

Plus you only need top level categories.

2023-12-01 13:09 UTC, mhaack commented on blocks/product-category-list/filter.js
> +const createFilters = (items, activeTag) => {
Is there a plan to us this for the blog/news hub as well?

2023-12-01 13:09 UTC, mhaack approved these changes

2023-12-01 15:16 UTC, rgravitvl commented on blocks/product-category-list/filter.js
> +const createFilters = (items, activeTag) => {
We can use

2023-12-01 16:00 UTC, rgravitvl commented on blocks/product-category-list/miniCard.js
done

2023-12-05 09:14 UTC, davenichols-DHLS requested changes
Hi @rgravitvl , sorry I have noticed that if I tag multiple OpCos then the filter breaks:

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/7243ac42-f425-4652-b072-901c2e2964e7)

2023-12-05 15:44 UTC, davenichols-DHLS approved these changes
Approved - we will raise a task about anchoring down to the component when you click on it.

2023-12-05 15:55 UTC, merged