fix: footer sizing
hlxsites/danaher-ls-aem pull request #56
Opened 2023-09-12 11:01 UTC by dicagno

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #55 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://fix-footer-sizing--danaher-ls-aem--hlxsites.hlx.page/

2023-09-12 11:32 UTC, mhaack commented
Can you make it little smaller. The height of the footer is still bigger then original.

2023-09-12 11:46 UTC, duynguyen approved these changes

2023-09-14 08:10 UTC, mhaack approved these changes

2023-09-14 09:10 UTC, davenichols-DHLS approved these changes
Looks great, thank you.

2023-09-14 09:12 UTC, mhaack requested changes

2023-09-14 09:12 UTC, mhaack commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
Should we many detect this by the link text or href = "#" instead of the position. The links might get re-arranged and this will break.

2023-09-14 09:14 UTC, dicagno commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
I would prefer link href rather than text.
I agree on using the href. BTW can we use a more specific hash like #manage-cookies?

2023-09-14 11:06 UTC, dicagno commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
yet another solution might be preserving this class in the conversion process.

2023-09-14 11:50 UTC, mhaack commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
That would be better. But not sure if it still works.

@bpauli can we, for the footer, detected the hash link and if it has the special class `ot-sdk-show-settings` we rewrite it and add the class name as hash value?

2023-09-14 12:13 UTC, dicagno commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
Hi @mhaack we have already applied a similar solution using the hash, and then restoring the href="#" back during the rendering process.

2023-09-14 12:38 UTC, mhaack commented on blocks/footer/footer.js
> +    a.classList.add('ot-sdk-show-settings');
Yep saw @bpauli 's PR

2023-09-14 12:38 UTC, mhaack approved these changes

2023-09-14 12:42 UTC, merged