503 implement carousel UI block
hlxsites/danaher-ls-aem pull request #561
Opened 2023-12-07 10:22 UTC by amlan18041996

Fix #503 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
- After: https://503-implement-carousel-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/products
- After: https://503-implement-carousel-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/product1
- After: https://503-implement-carousel-ui-block--danaher-ls-aem--hlxsites.hlx.page/us/en/product3

2023-12-07 11:21 UTC, davenichols-DHLS requested changes
This is really great Amlan.  I did notice if you click on the arrows to go from 5 to 1 or 1 to 5 (back) then it appears to break.

2023-12-08 08:22 UTC, rgravitvl commented
@amlan18041996 Please fix the lint issues. Thanks.

2023-12-11 09:33 UTC, davenichols-DHLS commented
@mhaack  and @duynguyen  - can you please review this?

2023-12-11 16:42 UTC, davenichols-DHLS requested changes
Hi @amlan18041996 , as discussed:

- Brand name (Leica Microsystems in the example) is not in the small purple text if it’s been added
- If you add a second optional button it is not styled, it should be as per the mockup
- Image on the carousel should be object-cover
- The controls should be in line with the text
- The control circles from w-10, h-10 to w-8, h-8
- The control svgs in the cicles from w-4,h-4 to w-3,h-3
- There shouldn’t be any padding-top if the carousel is the first component or at the top
- Carousel Min Height from 44rem to 37rem

2023-12-12 17:11 UTC, davenichols-DHLS approved these changes
I am loving this.  Thank you very much.  @duynguyen , @mhaack  and @rgravitvl  - can you please review?

2023-12-12 22:21 UTC, duynguyen commented on blocks/carousel/carousel.js
> +  const groupElements = [...block.children].reduce((prev, curr) => {
wondering if you really need to run this loop?
you run the nested loop anyway below, can the children array just retrieved there directly?

2023-12-12 22:30 UTC, duynguyen commented on blocks/carousel/carousel.js
> +      ele.map((el, index) => {
the slide decoration is quite specific to a slide of 2 columns (2 children). Do we need a loop here?
another idea: just querySelector the div containing img and the div without img.

2023-12-12 22:37 UTC, duynguyen commented on blocks/carousel/carousel.js
> +            if (heading.nextElementSibling) {
can this be applied more generic? all p elements after the heading that are not button-container should get this style. in case there are more than one paragraphs in the content.

2023-12-12 22:45 UTC, duynguyen commented on blocks/carousel/carousel.js
> +          if (el.querySelector('.button-container')) {
how about:
```
const buttonContainers = el.querySelectorAll('.button-container');
if(buttonContainers.length > 0) {
  // create actions wrapper
  // run the loop
}
```
also, let's make sure the old button-container is removed afterwards.

2023-12-12 22:46 UTC, duynguyen commented on scripts/Carousel.js
> +export default function Carousel(carouselEl, items, options) {
very nice that you made this carousel very generic and reusable 👏

2023-12-13 15:42 UTC, duynguyen approved these changes
approving to unblock release, comments can be addressed in a follow-up later.

2023-12-13 15:43 UTC, mhaack approved these changes

2023-12-13 15:44 UTC, merged