560 style update opco home page
hlxsites/danaher-ls-aem pull request #568
Opened 2023-12-11 09:31 UTC by rgravitvl

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #560 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home
- After: https://560-style-update-opco-home-page>--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home

2023-12-11 10:00 UTC, mhaack commented on blocks/social-feeds/social-feeds.js
> +  block.parentNode.parentNode.classList.remove('top-border');
Why this shuffle, why not keep the class where it is and style there?

2023-12-11 14:52 UTC, duynguyen commented on blocks/columns/columns.js
> +    cols.forEach((row) => {
so `cols` is from `[...block.firstElementChild.children]`. is it intended?
the old code with row and col seem more understandable to me.

2023-12-11 14:55 UTC, duynguyen requested changes
some css changes have broken many headings

2023-12-11 14:55 UTC, duynguyen commented on blocks/columns/columns.css
> +  @apply py-2 px-6 !text-white;
this seems to break a lot of headings, even on home page

2023-12-12 04:45 UTC, rgravitvl commented on blocks/columns/columns.js
> +    cols.forEach((row) => {
The old code was vice versa. I think now its correct. I can explain if needed. Thanks

2023-12-12 10:05 UTC, duynguyen commented on blocks/columns/columns.css
> +.bottom-border-right > div > div > p:nth-child(3n+3) {
is `.bottom-border-right` intended to be a class of `.columns` only?
then I would do `.columns.bottom-border-right` to avoid ambiguity, e.g. the same variant name being used in other blocks.

2023-12-12 10:05 UTC, duynguyen commented on blocks/columns/columns.css
> +.bg-color-right > div > div:nth-child(2) > p > a {
same as above, `.columns..bg-color-right`

2023-12-12 10:07 UTC, duynguyen commented on styles/tailwind.css
> +  main .section .top-border > div {
I see on https://560-style-update-opco-home-page--danaher-ls-aem--hlxsites.hlx.page/us/en/products/brands/opco-home: top-border is for a section, would this work?

2023-12-12 10:11 UTC, rgravitvl commented on styles/tailwind.css
> +  main .section .top-border > div {
Yes, If I get question correctly. As we have bg colors in full layout, we have added top border as well and its working as expected.

2023-12-12 10:16 UTC, rgravitvl commented on blocks/columns/columns.css
> +.bg-color-right > div > div:nth-child(2) > p > a {
Done

2023-12-12 10:16 UTC, rgravitvl commented on blocks/columns/columns.css
> +.bottom-border-right > div > div > p:nth-child(3n+3) {
Done

2023-12-12 10:30 UTC, duynguyen approved these changes

2023-12-12 10:41 UTC, merged