Product Family Page Play Vidyard Video
hlxsites/danaher-ls-aem pull request #630
Opened 2023-12-29 11:23 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #629

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://629-products-vidyard-video--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/cloneselect-imagers

2024-01-02 09:35 UTC, mhaack requested changes

2024-01-02 09:35 UTC, mhaack commented on blocks/embed/embed.js
> +const embedVideos = (block, url, autoplay) => {
I suggest to keep the `embedVimeo` and add a `embedVidyard` to be more flexible for the different video players.

2024-01-02 10:38 UTC, sharanagoudapatil commented on blocks/embed/embed.js
> +const embedVideos = (block, url, autoplay) => {
Hi @mhaack - I've made the changes. Please review. Thanks.

2024-01-02 12:46 UTC, rgravitvl approved these changes

2024-01-02 15:08 UTC, duynguyen approved these changes

2024-01-02 15:10 UTC, davenichols-DHLS approved these changes
Appears to work for me.

2024-01-04 11:27 UTC, mhaack approved these changes

2024-01-04 11:45 UTC, merged