Product Family detail page - specification attributes
hlxsites/danaher-ls-aem pull request #644
Opened 2024-01-09 09:35 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://643-product-spec-attributes--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/548021-molecular-devices

2024-01-09 10:42 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +  if (localStorage.getItem('product-hero')) {
let's use the common script `getProductResponse()` that Ravi added in #640

2024-01-09 11:01 UTC, davenichols-DHLS approved these changes
Please see Duy's comments, but I approve from the UX point of view, the tables are looking good.

2024-01-09 14:03 UTC, sharanagoudapatil commented on blocks/product-specifications/product-specifications.js
> +  if (localStorage.getItem('product-hero')) {
@duynguyen - I've modified as per above comments. Please have a look. Thanks.

2024-01-09 15:37 UTC, davidzochowski commented
@sharanagoudapatil I tried to test with another page but it still renders the biomek family.
https://643-product-spec-attributes--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/7181375-molecular-devices

2024-01-09 15:39 UTC, davidzochowski commented on blocks/product-specifications/product-specifications.js
As part of the attributejson, I added another field called "unit". Would you please append the unit (assuming non-empty/non-null) to the value in the table?

2024-01-09 15:39 UTC, davidzochowski submitted a review, later dismissed
As part of the attributejson, I added another field called "unit". Would you please append the unit (assuming non-empty/non-null) to the value in the table?

Edit: For the attribute values that come in a list, could you add a space between the values? For the example page you used, instead of T1020_WB,T1070,T190F_LLS,T230,T230_LSS,... , could it be T1020_WB, T1070, T190F_LLS, T230, T230_LSS, ... (there are spaces after each comma)

2024-01-11 06:44 UTC, sharanagoudapatil commented
@davidzochowski - Please review the changes as requested. Thanks.

2024-01-11 14:28 UTC, duynguyen requested changes
thanks @sharanagoudapatil , I left some comments.

2024-01-11 14:28 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +      if (attrJson.length > 0) {
this condition might be redundant

2024-01-11 14:28 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +              h1({ class: 'text-xl font-normal leading-6 text-black' }, item.label),
do we want an h1 here? then there would be multiple h1 on the page, and the a11y score would be affect. let's revise the heading level here.

2024-01-11 14:28 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +          if (item.value.length) {
redundant condition

2024-01-11 14:28 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +      block.innerHTML = '';
if these 2 lines are common for both conditions, let's move it outside of the if and remove it in the else.

2024-01-11 14:32 UTC, davidzochowski commented
@sharanagoudapatil I was thinking something like this.
<img width="660" alt="Screenshot 2024-01-11 at 9 31 17 AM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/f383a215-9696-41c6-87f8-5b590699695b">

2024-01-12 05:19 UTC, sharanagoudapatil commented
@davidzochowski - Done with the changes. Pls check. Thanks.

2024-01-12 05:22 UTC, sharanagoudapatil commented on blocks/product-specifications/product-specifications.js
> +              h1({ class: 'text-xl font-normal leading-6 text-black' }, item.label),
Hi @duynguyen - I've made the changes for rest of the comments. But will connect for this H1 tag as I'm not getting your comments here. Thanks.

2024-01-12 11:04 UTC, sharanagoudapatil commented on blocks/product-specifications/product-specifications.js
> +              h1({ class: 'text-xl font-normal leading-6 text-black' }, item.label),
As as discussed with @davenichols-DHLS I've made the table headings from h1 to h2 with the same css changes. Please have a look. Thanks.

2024-01-12 11:12 UTC, duynguyen approved these changes
minor comment. good with me to merge.

2024-01-12 11:12 UTC, duynguyen commented on blocks/product-specifications/product-specifications.js
> +    const attrContainer = div({ class: 'block' });
let's remove the wrapper div as it's not needed

2024-01-12 12:05 UTC, sharanagoudapatil commented on blocks/product-specifications/product-specifications.js
> +    const attrContainer = div({ class: 'block' });
Removed.

2024-01-12 14:19 UTC, davidzochowski commented
@sharanagoudapatil Looks good to me. Approved

2024-01-12 14:19 UTC, davidzochowski approved these changes

2024-01-16 16:26 UTC, merged