feat: columns styling
hlxsites/danaher-ls-aem pull request #67
Opened 2023-09-13 22:18 UTC by dicagno

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #13 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://feat-column-block--danaher-ls-aem--hlxsites.hlx.page/

2023-09-15 15:01 UTC, mhaack commented on blocks/columns/columns.css
Can we try to keep it consistent - either Tailwind or plain css, but no mix. This is not developer friendly.

2023-09-15 15:03 UTC, mhaack requested changes

2023-09-15 15:03 UTC, mhaack commented on blocks/columns/columns.css
> +  line-height: 40px;
Speaking about consistency ... `leading-10` sets line-height already and `text-sm` sets font-size and line-height.

2023-09-15 18:29 UTC, dicagno commented on blocks/columns/columns.css
I don't think it's not developer friendly, it depends on the use case.
 Here, for example, the original website doesn't make use of Tailwind classes for the CTA, hence keeping the CSS provides a 1:1 mapping that might be helpful, especially in case of fixes.
Regarding consistency, yeah it might apparently look like it is lacking, but the `@apply` directive is designed to be used in the scope of css selectors, together with pure css.
However, to speed up the process, I am providing the Tailwind version in the next commit, and then we can decide.

2023-09-15 18:31 UTC, dicagno commented on blocks/columns/columns.css
> +  line-height: 40px;
yeah, might be a leftover

2023-09-15 19:43 UTC, mhaack commented on blocks/columns/columns.css
> +  font-size: 18px;
Another leftover.

2023-09-15 19:44 UTC, mhaack commented on blocks/columns/columns.css
See https://tailwindcss.com/docs/reusing-styles#avoiding-premature-abstraction on the usage of `@apply`.

We are not aiming for 1:1 mapping, keeping it close to old structure can help but it not the primary goal. This is a new site with different and clean HTML markup we need to style.

I know the old side did a mix of TW and plain classes. Sometimes more, sometimes less. I personally consider this as bad and we should not repeat it.

2023-09-17 12:00 UTC, dicagno commented on blocks/columns/columns.css
yeah, makes sense

2023-09-18 07:25 UTC, mhaack approved these changes

2023-09-18 07:30 UTC, merged