[Coveo] Coveo API Updates #664
hlxsites/danaher-ls-aem pull request #670
Opened 2024-01-17 18:06 UTC by davidzochowski

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #[664](https://github.com/hlxsites/danaher-ls-aem/issues/664)

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
- After: https://664-coveo-coveo-api-updates--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges
- After: https://664-coveo-coveo-api-updates--danaher-ls-aem--hlxsites.hlx.page/us/en/products/sku/c63128-beckman-coulter-life-sciences

2024-01-17 18:10 UTC, davenichols-DHLS approved these changes
Looks good to me.  @rgravitvl , @mhaack  and @duynguyen  - can you please review?

2024-01-18 05:00 UTC, rgravitvl approved these changes

2024-01-23 15:53 UTC, mhaack requested changes

2024-01-23 15:53 UTC, mhaack commented on scripts/delayed.js
> +  if (window.location.pathname.indexOf('/products/family/') > 0 || window.location.pathname.indexOf('/products/sku/') > 0 || window.location.pathname.indexOf('/products/bundles/') > 0 ){
This should be based on the page type instead of the URL. All product pages have `<meta name="template" content="ProductDetail">`.

```suggestion
  if (getMetadata('template') === 'ProductDetail' ){
```

2024-01-23 16:10 UTC, davidzochowski commented
It wasn't working on the .hlx.page because there was a conditional to have it not fire on those pages. It should fire on all pages now except localhost.

2024-01-23 16:15 UTC, duynguyen commented on scripts/delayed.js
> -  && !document.location.hostname.includes('.hlx.page')
this will also allow GTM scripts to run on hlx.page. How about keeping the old condition and we test this PR directly on hlx.live?

2024-01-24 10:15 UTC, mhaack approved these changes

2024-01-24 10:16 UTC, mhaack commented on scripts/delayed.js
> +  const cats = document.querySelector('.hero-default-content .categories');
@davidzochowski this maybe can be combined with line 101-104 below?

2024-01-25 09:55 UTC, davenichols-DHLS commented
Hi @davidzochowski  - sorry, I went to merge, but saw that there are conflicts.  Please can you resolve and then we can merge.  Thanks.

2024-01-25 14:16 UTC, davidzochowski commented
@davenichols-DHLS Conflicts resolved

2024-01-25 16:14 UTC, merged