initial commit for eventcard converter
hlxsites/danaher-ls-aem pull request #73
Opened 2023-09-15 09:08 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://<branch>--danaher-ls-aem--hlxsites.hlx.page/

2023-09-18 14:19 UTC, bpauli requested changes
@sharanagoudapatil The PR looks already very good. I added my suggested improvements. Beside that,  it would be great if you can modify the existing `createFullLayoutSection` so we only add a section metadata to a block when the styles are not empty. For the Landingpage we didn't have this case.

2023-09-18 14:19 UTC, bpauli commented on package.json
> +    "lint:js": "eslint . --fix",
I think we should not apply fixes automatically.

2023-09-18 14:19 UTC, bpauli commented on tools/importer/import.js
> +      fl.before(document.createElement('hr'));
We should only create a new section when this is really required (for example by provided a dedicated section metadata)

2023-09-21 08:48 UTC, bpauli approved these changes

2023-09-21 08:52 UTC, merged

2023-09-21 08:54 UTC, sharanagoudapatil commented
@bpauli - Thanks much for your time/help to connect on this morning. 
Now we are good with the changes. Thanks.