860 [Solutions] Products list missing analytics
hlxsites/danaher-ls-aem pull request #862
Opened 2024-03-05 08:44 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #860 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://860-prod-list-missing-analytics--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/dm-il-led-inverted-laboratory-microscopes

2024-03-07 21:39 UTC, davidzochowski commented on scripts/commerce.js
> +      documentUri: res.raw.uri,
This should be res.uri, not res.raw.uri

2024-03-07 21:44 UTC, davidzochowski commented on scripts/commerce.js
> +    clientId,
This value is showing as null when I test on .hlx.page

2024-03-07 21:49 UTC, davidzochowski commented on scripts/commerce.js
> +    numberOfResults: response.length,
This should be the total number of results, not just the number shown. For the test page in the PR, that would be the 'totalCount' value from the query response.

2024-03-07 22:13 UTC, davidzochowski commented on scripts/commerce.js
> +function getProductsOnSolutionsApiPayload(qParam) {
The payload for the Search Query needs to be updated. Do you want to do this in this branch or add as a new branch?

2024-03-07 22:38 UTC, davidzochowski commented on blocks/product-card/product-card.js
> +        onClickCoveoAnalyticsResponse(clickUri.split('/').pop(), idx);
Im getting a NS_BINDING_ABORTED response when making the click event. This is because the page redirect is happening before the analytics event has finished sending to Coveo. Would you be able to delay the page redirect until you get a response from this analytics call?

2024-03-07 22:40 UTC, davidzochowski requested changes
Added comments

2024-03-08 11:48 UTC, sharanagoudapatil commented on scripts/commerce.js
> +    clientId,
Hi @mhaack - I'm facing this issue when we run this test page - https://860-prod-list-missing-analytics--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products but working fine on http://localhost:3000/us/en/solutions/mabs/cell-line-development/products. Any idea on this?

2024-03-08 11:49 UTC, sharanagoudapatil commented on scripts/commerce.js
> +      documentUri: res.raw.uri,
updated with the changes.

2024-03-08 11:49 UTC, sharanagoudapatil commented on scripts/commerce.js
> +    numberOfResults: response.length,
updated with the changes.

2024-03-08 11:50 UTC, sharanagoudapatil commented on blocks/product-card/product-card.js
> +        onClickCoveoAnalyticsResponse(clickUri.split('/').pop(), idx);
I've added the 3ms delay. will test it with this change.

2024-03-08 13:38 UTC, davidzochowski commented on scripts/commerce.js
> +      await makeCoveoAnalyticsApiRequest('/rest/v15/analytics/search', 'categoryProductKey', getCoveoAnalyticsPayload(fullResponse.duration, fullResponse.searchUid, fullResponse));
Since the fullResponse object is being passed in, there's no need to have three separate parameters that all use the same object, let's just have the one parameter and get the values within the cooresponding method

2024-03-08 14:29 UTC, sharanagoudapatil commented on scripts/commerce.js
> +      await makeCoveoAnalyticsApiRequest('/rest/v15/analytics/search', 'categoryProductKey', getCoveoAnalyticsPayload(fullResponse.duration, fullResponse.searchUid, fullResponse));
Done.

2024-03-08 15:03 UTC, davidzochowski approved these changes

2024-03-08 15:05 UTC, sharanagoudapatil commented on scripts/commerce.js
> +function getProductsOnSolutionsApiPayload(qParam) {
As discussed, will add these changes as a separate task/branch. Thanks.

2024-03-08 15:07 UTC, sharanagoudapatil commented on scripts/commerce.js
> +    clientId,
Added the condition to check clientId to update the payload.

2024-03-08 15:08 UTC, merged