881 [Solutions] Update Search Payload
hlxsites/danaher-ls-aem pull request #885
Opened 2024-03-11 07:25 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #881 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://881-update-search-payload--danaher-ls-aem--hlxsites.hlx.page/

2024-03-11 13:32 UTC, davidzochowski requested changes
@sharanagoudapatil You updated the analytics payload. This change is for the Search payload.

2024-03-11 15:25 UTC, sharanagoudapatil commented
@davidzochowski - I've updated Search payload. Please have a look. Thanks.

2024-03-11 17:29 UTC, davidzochowski commented on scripts/commerce.js
> +      context_internal: false,
This value should be based off of the exclude-from-analytics cookie. The same as what is being used for the other payloads.

2024-03-11 17:29 UTC, davidzochowski commented on scripts/commerce.js
>        internal: false,
This value should be based off of the exclude-from-analytics cookie. The same as what is being used for the other payloads.

2024-03-11 17:30 UTC, davidzochowski commented on scripts/commerce.js
> +    language: 'en',
set this field to 'locale' instead of 'language'

2024-03-11 17:31 UTC, davidzochowski submitted a review, later dismissed
Requested changes

2024-03-11 17:33 UTC, davidzochowski commented on scripts/commerce.js
> +      context_host: window.DanaherConfig.host,
Some code cleanup, you're already creating a host variable on line 129. could use that or remove the variable and use the config variable for line 146

2024-03-11 17:36 UTC, davidzochowski commented on scripts/commerce.js
>    const payload = {
Missing the 'analytics' block. Some of the fields should be within that block.

2024-03-12 04:33 UTC, sharanagoudapatil commented on scripts/commerce.js
> +      context_internal: false,
Done.

2024-03-12 04:48 UTC, sharanagoudapatil commented on scripts/commerce.js
> +    language: 'en',
updated.

2024-03-12 04:48 UTC, sharanagoudapatil commented on scripts/commerce.js
> +      context_host: window.DanaherConfig.host,
modified.

2024-03-12 04:48 UTC, sharanagoudapatil commented on scripts/commerce.js
>    const payload = {
updated.

2024-03-12 04:51 UTC, sharanagoudapatil commented on scripts/commerce.js
>        internal: false,
updated.

2024-03-12 13:51 UTC, davidzochowski commented
Checking Coveo analytics. There are two issues:
1. Change logic so that if clientid is null, do NOT send analytics payload
 Update line 198  if (fullResponse && fullResponse.results.length > 0 **&& clientId !== null**) {
2. For onClickCoveoAnalyticsPayload, need to add customData.contentIDValue and customData.contentIDKey
Logic is same as line 76+77 in delayed.js
      context_contentIDValue: window.location.href,
      context_contentIDValue: 'permanentid' //this can be hardcoded

2024-03-12 14:16 UTC, davidzochowski approved these changes

2024-03-12 14:18 UTC, merged