817 [Product] Product Recommendations from coveo
hlxsites/danaher-ls-aem pull request #892
Opened 2024-03-12 06:39 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #817 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://817-product-recommendations-ui--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/optima-auc-analytical-ultracentrifuge
- After: https://817-product-recommendations-ui--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges

2024-03-13 13:36 UTC, davidzochowski commented on scripts/commerce.js
> +      itemIds: itemIds[0],
mlParameters can have both 'itemId' (single) and 'itemIds' (multiple). Different strategies use either one or the other. In the case for the 'frequentViewed' model, we need to use the 'itemId' (single).

2024-03-13 13:37 UTC, davidzochowski commented on scripts/commerce.js
> +  const payload = {
Let's add the 'fieldToInclude' field as part of the payload. With this, we can restrict which field values Coveo will return so that the response size is smaller.
```
    "fieldsToInclude": [
        "title",
        "description",
        "categoriesname",
        "images"
    ],
```

2024-03-13 13:38 UTC, davidzochowski commented on scripts/commerce.js
> +  const payload = {
This payload is missing the other attributes. It should be similar in size to what the solution payload would look like. I provided an example in the issue.

2024-03-13 16:34 UTC, davidzochowski requested changes
added comments

2024-03-13 16:34 UTC, davidzochowski commented on scripts/commerce.js
> +  const payload = {
Payload needs to be updated, I provided an example in the Issue.

2024-03-13 16:35 UTC, davidzochowski commented on scripts/commerce.js
> +  const payload = {
Payload needs to be updated. Example provided in the Issue.

2024-03-13 16:35 UTC, davidzochowski commented on scripts/scripts.js
> +    productRecommendationsKey: 'xxea4d2c40-26e7-4e98-9377-d8ebe3f435ea',
Production API key added in the Issue

2024-03-26 15:15 UTC, sharanagoudapatil commented on scripts/commerce.js
> +      itemIds: itemIds[0],
updated with the changes.

2024-03-26 15:16 UTC, sharanagoudapatil commented on scripts/commerce.js
> +  const payload = {
updated with the changes.

2024-03-26 15:16 UTC, sharanagoudapatil commented on scripts/commerce.js
> +  const payload = {
updated with the changes.

2024-03-26 15:16 UTC, sharanagoudapatil commented on scripts/commerce.js
> +  const payload = {
updated with the changes. Pls verify.

2024-03-28 07:58 UTC, sharanagoudapatil commented
@davidzochowski - UI changes completed. Please review. Thanks.

2024-03-28 15:13 UTC, davidzochowski approved these changes
LGTM

2024-04-03 18:33 UTC, davidzochowski commented on blocks/product-recommendations/product-recommendations.js
> +          'Frequently viewed together',
Let's capitalize this to 'Frequently Viewed Together'.

2024-04-04 08:05 UTC, merged