868 blogsnews tags list
hlxsites/danaher-ls-aem pull request #913
Opened 2024-03-15 12:23 UTC by sharanagoudapatil

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #868 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://868-blogsnews-tags-list--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/biotherapeutic-development-partnerships
- After: https://868-blogsnews-tags-list--danaher-ls-aem--hlxsites.hlx.page/us/en/news/scientists-can-study-neuronal-morphology-harnessing-the-power-of-ai

2024-03-18 11:54 UTC, rgravitvl approved these changes

2024-03-18 16:52 UTC, davenichols-DHLS requested changes
Looks great.  For the email icon, can you please add this code:

`<a href="mailto:?subject=&amp;body=[sub]" onclick="this.href = this.href.replace('[sub]', encodeURIComponent(window.location))" ......`

2024-03-21 05:03 UTC, sharanagoudapatil commented
> Looks great. For the email icon, can you please add this code:
> 
> `<a href="mailto:?subject=&amp;body=[sub]" onclick="this.href = this.href.replace('[sub]', encodeURIComponent(window.location))" ......`

@davenichols-DHLS - I've updated the email link. Please verify.

2024-03-21 11:11 UTC, davenichols-DHLS approved these changes

2024-03-21 11:11 UTC, merged