866 MenuBar Re-design Changes
hlxsites/danaher-ls-aem pull request #977
Opened 2024-03-27 20:06 UTC by amlan18041996

Fix #866 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://866-rebrand-menu-bar-design--danaher-ls-aem--hlxsites.hlx.page/

2024-04-04 05:32 UTC, rgravitvl commented
HI @amlan18041996 ,

Could you please check below issue?. It loads incorrect menu on initial click.
Steps to reproduce: 
1. Open home page from branch
2. Scroll down for hamburger icon in menu
3. Click on hamburger icon
4. You will below screen shot

<img width="946" alt="image" src="https://github.com/hlxsites/danaher-ls-aem/assets/12641714/6fce7bd0-4cff-41c6-a4a1-4e13dab6af0e">

2024-04-04 05:36 UTC, rgravitvl requested changes
Already commented

2024-04-08 10:41 UTC, davenichols-DHLS approved these changes
I like it - going to review with Anthony and then will push.

2024-04-08 10:42 UTC, davenichols-DHLS commented
> * https://866-rebrand-menu-bar-design--danaher-ls-aem--hlxsites.hlx.page/

@rgravitvl  and @amlan18041996  - this looks like it is fixed now?  @rgravitvl  - are you happy to approve?

2024-04-08 14:47 UTC, rgravitvl reviewed
Use all Icon form Icon SVG

2024-04-08 14:47 UTC, rgravitvl commented on blocks/header/header.js
> +  hamburgerIcon.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" viewBox="0 0 24 24" class="w-8 h-8 fill-current"><path fill-rule="evenodd" d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a
use Icon from icon.svg

2024-04-10 09:17 UTC, merged